### ISSUE TITLE
Hide from menu when not logged in

### ISSUE THREAD

**Issue by andersonit** [mlongo4290/netbox-ipv4-tools#1]
Hello, is there a way to hide the plugin from the side menu when the users are not logged in?  I don't want people outside my organization to be able to browse or use the IP calculator.  Thanks.

**Comment by mlongo4290** [comment]
Hi @andersonit,
I can't find a comprehensive guide to properly use permissions for plugins.
But i release 1.0.3 the menu is still visible but the forms to use ipv4 tools requires a logged user, if not you are redirected to login page.

Let me know, if it works i'll close the issue

**Comment by andersonit** [comment]
Hi, That should be OK for now.  I prefer to have "LOGIN_REQUIRED = True" in the configuration.py so anyone not logged in will be redirected to the login page instead of the main dashboard - which would make my initial request irrelevant.  The problem is I also have the netbox-otp-plugin installed and there is a bug with it that breaks the login page when login required is set, so I don't have it set for now.  There is an open issue on that project so when that's fixed everything will be working like I'd prefer.  Thanks for taking a look and responding!
